<TimeWidget>:

    Label:
        text: root.time
        color: 0.85,0.85,0.85,1
        font_size: 35
        text_size: self.size
        size_hint: (1,1)
        pos: root.width - 310, root.top - 70
        halign: 'left'
    Label:
        text: root.date
        color: 0.85,0.85,0.85,1
        font_size: 20
        text_size: self.size
        size_hint_x: 1.0
        size: (270,90)
        pos: root.width - 310, root.top - 110
        halign: 'left'